# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bce2cd18720cf2cdab2cba305c6d5b6940c6e175611290a49b680c7758060b6213fbe4f6468f8b8331268b74a858addef69c9ff3b2ec2e44bc59d7e633023a01

test:
  secret_key_base: 300a4cb9323548a5b1a26a184470dcb367088fdbf7a730de115e9bd116ded109efb76fc20c00163ad8effb3ea879c44f9fa05e5e66919461b3904bfa8990fa2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
